name: Fetch Discord Messages

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes

jobs:
  fetch-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Fetch Discord messages
        run: node fetchMessages.js # Adjust the path if your script is in a directory
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add lastMessage.json
          git commit -m "Update Discord message" -a || echo "No changes to commit"
          git push
